version: "3.0"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - docker-network
    ports:
      - 9000:9000
    depends_on:
      - db

  queue-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - docker-network
    depends_on:
      - db
    command: php artisan queue:work

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./laravel-best:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - docker-network
    depends_on:
      - backend

  redis:
    image: bitnami/redis:7.2
    platform: linux/amd64
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - docker-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - docker-network

  db:
    image: hibitdev/sqlite:latest
    container_name: sqlite
    hostname: sqlite.hibit
    restart: always
    ports:
      - "8191:8191"
    volumes:
      - ./sqlite:/db
    command: ["tail", "-f", "/dev/null"] # Keeps the container running
    networks:
      - docker-network

volumes:
  db-data:
  redis-data:

networks:
  docker-network:
    driver: bridge
